// <auto-generated />
using GraAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GraAPI.Migrations
{
    [DbContext(typeof(GryDb))]
    [Migration("20251220163531_Lista gier")]
    partial class Listagier
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("GraAPI.Gry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tytul")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WszystkieGry");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Tag = "RPG",
                            Tytul = "Wiedźmin 3"
                        },
                        new
                        {
                            Id = 2,
                            Tag = "Sportowe",
                            Tytul = "FIFA 23"
                        },
                        new
                        {
                            Id = 3,
                            Tag = "RPG",
                            Tytul = "Cyberpunk 2077"
                        },
                        new
                        {
                            Id = 4,
                            Tag = "MOBA",
                            Tytul = "League of Legends"
                        },
                        new
                        {
                            Id = 5,
                            Tag = "MOBA",
                            Tytul = "Dota 2"
                        },
                        new
                        {
                            Id = 6,
                            Tag = "FPS",
                            Tytul = "Counter-Strike 2"
                        },
                        new
                        {
                            Id = 7,
                            Tag = "FPS",
                            Tytul = "Valorant"
                        },
                        new
                        {
                            Id = 8,
                            Tag = "Survival",
                            Tytul = "Minecraft"
                        },
                        new
                        {
                            Id = 9,
                            Tag = "Wyścigowe",
                            Tytul = "Forza Horizon 5"
                        },
                        new
                        {
                            Id = 10,
                            Tag = "RPG",
                            Tytul = "Elden Ring"
                        },
                        new
                        {
                            Id = 11,
                            Tag = "Strategiczne",
                            Tytul = "StarCraft II"
                        },
                        new
                        {
                            Id = 12,
                            Tag = "Strategiczne",
                            Tytul = "Age of Empires IV"
                        },
                        new
                        {
                            Id = 13,
                            Tag = "Roguelike",
                            Tytul = "Hades"
                        },
                        new
                        {
                            Id = 14,
                            Tag = "Roguelike",
                            Tytul = "Dead Cells"
                        },
                        new
                        {
                            Id = 15,
                            Tag = "FPS",
                            Tytul = "Call of Duty"
                        },
                        new
                        {
                            Id = 16,
                            Tag = "Symulator",
                            Tytul = "The Sims 4"
                        },
                        new
                        {
                            Id = 17,
                            Tag = "Sportowe",
                            Tytul = "F1 24"
                        },
                        new
                        {
                            Id = 18,
                            Tag = "RPG",
                            Tytul = "Diablo IV"
                        },
                        new
                        {
                            Id = 19,
                            Tag = "Survival",
                            Tytul = "Terraria"
                        },
                        new
                        {
                            Id = 20,
                            Tag = "FPS",
                            Tytul = "Apex Legends"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
